#!/usr/bin/env bash
#
# One-time Vercel setup: npm run setup:vercel
#
# Creates the project, connects it to GitHub, provisions a Blob store and sets
# every environment variable the bot needs. Safe to re-run: each step checks
# whether it has already been done.
#
# Requires `vercel login` first, as the account that owns the target scope.
# Deliberately leaves TRADING_ENABLED=false and sets no API keys, so the worst
# this can produce is a paper-trading dashboard.

set -euo pipefail

SCOPE="${VERCEL_SCOPE:-mopras-projects}"
PROJECT="${VERCEL_PROJECT:-above-the-line}"
REPO="${GIT_REPO:-https://github.com/Mopra/above.the.line.git}"
BLOB_STORE="${BLOB_STORE:-above-the-line-state}"

V="vercel --scope $SCOPE"

say() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

say "Checking login"
who=$(vercel whoami 2>/dev/null || true)
if [ -z "$who" ]; then
  echo "Not logged in. Run: vercel login" >&2
  exit 1
fi
echo "Logged in as $who, targeting scope $SCOPE."

say "Linking the project"
if [ -f .vercel/project.json ]; then
  echo "Already linked; leaving .vercel alone."
else
  $V link --yes --project "$PROJECT"
fi

say "Connecting the GitHub repository"
# Idempotent in practice: reconnecting the same remote is a no-op.
$V git connect "$REPO" || echo "Could not connect git automatically; do it in the dashboard under Settings > Git."

say "Creating the Blob store"
# Private, because it holds the bot's position and trade log. src/lib/state.ts
# reads and writes with access: 'private', so a public store would mismatch.
# fra1 keeps the data in the EU rather than the iad1 default.
if $V blob create-store "$BLOB_STORE" --access private --region fra1; then
  echo "Created $BLOB_STORE."
else
  echo "Store already exists or could not be created; continuing."
fi

# --- Environment variables -------------------------------------------------
# Secrets are generated here rather than hardcoded, so they never live in git.
say "Setting environment variables"

set_env() {
  local name="$1" value="$2" flags="${3:-}"
  for target in production preview development; do
    # shellcheck disable=SC2086
    printf '%s' "$value" | $V env add "$name" "$target" --force $flags >/dev/null 2>&1 || true
  done
  echo "  set $name"
}

CRON_SECRET="${CRON_SECRET:-$(openssl rand -hex 32)}"
STATE_PREFIX="${STATE_PREFIX:-state-$(openssl rand -hex 8)}"

set_env CRON_SECRET "$CRON_SECRET" --sensitive
set_env STATE_PREFIX "$STATE_PREFIX" --sensitive

set_env TRADING_ENABLED false
set_env KILL_SWITCH false
set_env MARKET BTC-EUR
set_env MAX_ALLOCATION_EUR 95
set_env ACCOUNT_VALUE_CEILING_EUR 250
set_env SMA_DAYS 140
set_env SIGNAL_WEEKDAY 1
set_env STOP_LOSS_PCT 20
set_env MAX_TRADES_PER_MONTH 6
set_env BITVAVO_OPERATOR_ID 1
set_env DKK_PER_EUR 7.46
set_env TAX_RATE_GAIN_PCT 42
set_env TAX_RATE_LOSS_PCT 26

# Keep a local copy so `npm run dry-run` behaves like production, and so you
# can call /api/cron by hand. .env.local is gitignored.
say "Writing .env.local"
cat > .env.local <<ENVFILE
# Generated by scripts/setup-vercel.sh. Gitignored. Do not commit.
CRON_SECRET=$CRON_SECRET
STATE_PREFIX=$STATE_PREFIX
TRADING_ENABLED=false
KILL_SWITCH=false
MARKET=BTC-EUR
MAX_ALLOCATION_EUR=95
ACCOUNT_VALUE_CEILING_EUR=250
SMA_DAYS=140
SIGNAL_WEEKDAY=1
STOP_LOSS_PCT=20
MAX_TRADES_PER_MONTH=6
BITVAVO_OPERATOR_ID=1
DKK_PER_EUR=7.46
TAX_RATE_GAIN_PCT=42
TAX_RATE_LOSS_PCT=26
ENVFILE
echo "  wrote .env.local"

say "Done"
echo "Blob must be attached to the project in the dashboard if BLOB_READ_WRITE_TOKEN"
echo "is not already present. Check with: $V env ls production"
echo
echo "Then deploy:  $V deploy --prod"
